# Linear Algebra Quiz

*Instructions* - Download and/or copy this notebook to your code repository. Complete the blank items in code ceels to get the desired value(s). Save and upload (or push) to github when finished. 

In [2]:
#import required packages
import numpy as np

## Part 1: Solutions to Systems of Equations

Consider solving a linar system of equations represented by the matrix $\mathsf{M}$ and vector $\vec{b}$:

In [3]:
M = np.array([[1.0,  -4.0, -0.5, -2.5,  2.0],
              [-4.0,  3.0, -5.5, -5.5, -3.5],
              [-0.5, -5.5,  7.0, -2.0,  3.5],
              [-2.5, -5.5, -2.0, -2.0, -4.0],
              [ 2.0, -3.5, -3.5, -4.0,  1.0]])

b = np.array([1, -1, 2, -1, 0])

Use the code below to see the representation of $\mathsf{M}$ and $\vec{b}$ as a system of equations

In [4]:
for i in range(M.shape[0]):
    terms = []
    for j in range(M.shape[1]):
        terms.append("{1} x[{0}]".format(j, M[i, j]))
    print(" + ".join(terms), "=", b[i])

1.0 x[0] + -4.0 x[1] + -0.5 x[2] + -2.5 x[3] + 2.0 x[4] = 1
-4.0 x[0] + 3.0 x[1] + -5.5 x[2] + -5.5 x[3] + -3.5 x[4] = -1
-0.5 x[0] + -5.5 x[1] + 7.0 x[2] + -2.0 x[3] + 3.5 x[4] = 2
-2.5 x[0] + -5.5 x[1] + -2.0 x[2] + -2.0 x[3] + -4.0 x[4] = -1
2.0 x[0] + -3.5 x[1] + -3.5 x[2] + -4.0 x[3] + 1.0 x[4] = 0


We want to determine the solution vector $\vec{x}$ for the system, but let's try a different method than a direct call to `np.linalg.solve()`. Remember in class our discussion of QR factorisation. Start by $\mathsf{Q}$ and $\mathsf{R}$ from $\mathsf{M}$:

In [5]:
Q, R = ... # 1. Fill in the blank to complete the expression 

print("Matrix Q:")
print(Q)
print("\nMatrix R:")
print(R)

Matrix Q:
[[-0.19069252 -0.38369783  0.2353589   0.19143061 -0.85110096]
 [ 0.76277007  0.20945823  0.2937686   0.53280431 -0.06425455]
 [ 0.09534626 -0.57276632 -0.64791879  0.46549041  0.16238148]
 [ 0.47673129 -0.62096025  0.24565574 -0.55994303  0.11512035]
 [-0.38138504 -0.30862651  0.61494772  0.38633712  0.48153719]]

Matrix R:
[[-5.24404424  1.23950137 -3.05108029 -3.33711906 -5.00567859]
 [ 0.          9.808855   -2.64742234  3.42918349 -1.32996711]
 [ 0.          0.         -8.91246678 -3.85938929 -3.1928633 ]
 [ 0.          0.          0.         -4.76544345  2.77337183]
 [ 0.          0.          0.          0.         -0.88792002]]


An alternative way of solving the system of equations takes advantage of the QR form of M to rewrite the original expression as:
$$
\mathsf{R}\vec{x} = \mathsf{Q^T}\vec{b}
$$
where we have used the fact that $\mathsf{Q^T = Q^{-1}}$ given that Q is an orthogonal matrix. Run the cell below to verify this property of the matrix $\mathsf{Q}$:

In [6]:
print("Result of Q^T * Q: ")
print(Q.T @ Q)

Result of Q^T * Q: 
[[ 1.00000000e+00 -2.38047626e-16  1.71207867e-16  9.17985561e-17
  -4.74662378e-16]
 [-2.38047626e-16  1.00000000e+00 -2.49920791e-17  1.86556383e-16
  -1.61804431e-16]
 [ 1.71207867e-16 -2.49920791e-17  1.00000000e+00 -9.71704673e-18
   2.52528855e-17]
 [ 9.17985561e-17  1.86556383e-16 -9.71704673e-18  1.00000000e+00
   1.44993365e-16]
 [-4.74662378e-16 -1.61804431e-16  2.52528855e-17  1.44993365e-16
   1.00000000e+00]]


When using QR factorisation to solve a system of equations, it is typical to recast the RHS equation to:
$$
\vec{y} = \mathsf{Q^T}\vec{b}
$$

Following this the equation of intrest becomes:
$$
\mathsf{R}\vec{x} = \vec{y}
$$
Complete the code block below to find the solution of the system of equations

In [8]:
y = ....   # 2. Fill in the blank to complete the expression 

x = ... # 3. Fill in the blank to complete the expression 

print("The solution to the provided system of equations is: ", x)

The solution to the provided system of equations is:  [-0.43042175 -0.104166   -0.11273641  0.13709444  0.65006283]


Take a moment to verify that we get the same result using 'np.linalg.solve()' directly on $\mathsf{M}$:

In [9]:
x_M = np.linalg.solve(M, b) 

print("The solution to the provided system of equations is: ", x_M)

The solution to the provided system of equations is:  [-0.43042175 -0.104166   -0.11273641  0.13709444  0.65006283]


## 2. Matrix Diagonalization

Consider the example matrix $\mathsf{A}$ provided below:

In [11]:
A = np.array([[16, 10, 7],
              [10, -8, 0],
              [7, 0, 6]])

Find the eigenvalues and eigenvectors of $\mathsf{A}$:

In [13]:
eigvalues, eigvectors = ... # 4. Fill in the blank to complete the expression 

print(f"\nEigenvalues: {eigvalues}")
print(f"Eigenvectors:\n{eigvectors}")


Eigenvalues: [ 22.30499895 -11.96276574   3.65776679]
Eigenvectors:
[[-0.8793615  -0.36466577 -0.30617353]
 [-0.29017044  0.92023045 -0.2626348 ]
 [-0.37752413  0.14210843  0.91503045]]


Using the results of the above cell, we will perform dianolaliztaion on the original matrix $
\mathsf{A}$. Start by constructing the matricies $\mathsf{D}$ and $\mathsf{P}$

In [14]:
D = ...  # 4. Fill in the blank to complete the expression 

P = eigvectors

print("Matrix D:")
print(D)

print("\nMatrix P:")
print(P)

Matrix D:
[[ 22.30499895   0.           0.        ]
 [  0.         -11.96276574   0.        ]
 [  0.           0.           3.65776679]]

Matrix P:
[[-0.8793615  -0.36466577 -0.30617353]
 [-0.29017044  0.92023045 -0.2626348 ]
 [-0.37752413  0.14210843  0.91503045]]


Now find the inverse of P:

In [ ]:
P_inverse = ... # 5. Fill in the blank to complete the expression 

print("Matrix P-inverse:")
print(P_inverse)

Now verify the expression:
$$
\mathsf{A = P  D  P^{-1}}
$$

In [ ]:
print("Original Matrix A:")
print(A)

print("\nResult of PDP^-1:")
print((P@D@P_inverse))

Remember that values may not match exactly becuase of issues with machine precision, but they should be close to the original result if things are done correctly!